### ISSUE TITLE
Method to check for ThermoMSFileReader dependency

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#106]
MetaMorpheus crashes with funky nonspecific errors if ThermoMSFileReader isn't installed. Could we make a method to check for ThermoMSFileReader and return a more detailed exception and exception message if it isn't installed?

**Comment by stefanks** [comment]
https://stackoverflow.com/questions/3214573/how-do-i-check-if-a-com-dll-is-registered-in-c-sharp

https://msdn.microsoft.com/en-us/library/hss5hw09.aspx

These should go into ThermoDynamicData.InitiateDynamicConnection and ThermoStaticData.LoadAllStaticData

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/mzLib/pull/275
