### ISSUE TITLE
More detailed error for missing elements

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#163]
Loading a ModificationWithMassAndCf before loading elements produces an error that can be very difficult to diagnose. Let's make it more detailed when we have the chance.

![weird_error](https://cloud.githubusercontent.com/assets/16342951/25311078/46d08820-27bc-11e7-9790-aaceb572d1d1.PNG)

**Comment by stefanks** [comment]
Done in https://github.com/smith-chem-wisc/mzLib/pull/282

**Comment by acesnik** [comment]
:+1:
