### ISSUE TITLE
Find a new serializer that implements ISerializable for custom serialization

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#167]
Currently, we are using NetSerializer for serialization because it is fast and works with Dictionary objects.

However, it does not implement ISerializable, so we cannot implement custom serializers to avoid circular references like Element <-> Isotope. I drafted an custom serialization, which you can find [here](https://github.com/smith-chem-wisc/mzLib/compare/master...acesnik:custom_serialization?expand=1).

**Comment by stefanks** [comment]
Yes, so the current [Serializable] label on the Isotope class is slightly misleading. Since something in that class is not serializable, namely the link to the parent Element.

**Comment by acesnik** [comment]
Removed in https://github.com/smith-chem-wisc/mzLib/pull/168
