### ISSUE TITLE
Unhandled exception in deconvoluting mzML file converted from Bruker (.d)

### ISSUE THREAD

**Issue by seanydai** [smith-chem-wisc/mzLib#258]
I received this feedback when I ran the Decon code on a mzML file converted from Bruker data file (in .d)
![deconvoluting bruker converted mzml](https://user-images.githubusercontent.com/20566230/31571647-872c10b4-b05c-11e7-927d-51beac34fe2c.png)
What does this mean?

**Comment by stefanks** [comment]
Whoops, good catch! It's a bug, mzML reading is not enabled by default. I'll try to address this soon.

**Comment by stefanks** [comment]
Fixed in new release!
