### ISSUE TITLE
FlashLFQEngine crashed while running MM searchtask

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/mzLib#301]
[results.txt](https://github.com/smith-chem-wisc/mzLib/files/1767162/results.txt)

[SearchTaskconfig.txt](https://github.com/smith-chem-wisc/mzLib/files/1767163/SearchTaskconfig.txt)

**Comment by rmillikin** [comment]
empty scan maybe? can you put files on bison

**Comment by zrolfs** [comment]
Files are found at \\bison\share\Users\QL\Gygi_NatBiotech\RAW
Spectra files run include 01A-12A (No B's)
DB is only xml in the folder
