### ISSUE TITLE
Losing protein name in LoadProteinFasta written by FastaWriter

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#314]

**Comment by rmillikin** [comment]
is this still a bug? not exactly sure what you mean. you load in a fasta and the protein names aren't read in correctly? or you write a fasta (I didn't even know we had this capability), read it in, and the names are lost?

**Comment by acesnik** [comment]
No, I fixed this, and I just checked with a new test, added here https://github.com/smith-chem-wisc/mzLib/pull/364
