### ISSUE TITLE
New Modification Type to replace multiple different modification types

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/mzLib#348]
We've had trouble with localization, naming collisions, and keeping track of which modifications are in use/not in use. We also don't have robust modification reading. It is currently subject to crash from minor formating problems. Also, currently have no ability to add "comments" to mod text files. I'd like to change all this. I'm currently creating one modification class to rule them all. Here is the first draft. Like to hear your comments/edits/suggests. All complaints can be sent to /dev/null

using System;
using System.Collections.Generic;
using System.Text;

using Chemistry;
using MassSpectrometry;

namespace Proteomics
{
    public class ModificationGeneral
    {
        public string Id { get; private set; }
        public string Accession { get; private set; }
        public string ModificationType { get; private set; }
        public string FeatureType { get; private set; }
        public List<string> Target { get; private set; }
        public List<string> Positions { get; private set; }
        public ChemicalFormula ChemicalFormula { get; private set; }
        public double? MonoisotopicMass { get; private set; }
        public Dictionary<string, string> DatabaseReference { get; private set; }
        public Dictionary<string, string> TaxonomicRange { get; private set; }
        public List<string> Keywords { get; private set; }
        public Dictionary<DissociationType, List<double>> NeutralLosses { get; private set; }
        public Dictionary<DissociationType, List<double>> DiagnosticIons { get; private set; }
        public string FileOrigin { get; private set; }

        public ModificationGeneral()
        {
            this.Id = null;
            this.Accession = null;
            this.ModificationType = null;
            this.FeatureType = null;
            this.Target = new List<string>();
            this.Positions = new List<string>();
            this.ChemicalFormula = new ChemicalFormula();
            this.MonoisotopicMass = null;
            this.DatabaseReference = new Dictionary<string, string>();
            this.TaxonomicRange = new Dictionary<string, string>();
            this.Keywords = new List<string>();
            this.NeutralLosses = new Dictionary<DissociationType, List<double>>();
            this.DiagnosticIons = new Dictionary<DissociationType, List<double>>();
            this.FileOrigin = null;
        }
    }

}

**Comment by rmillikin** [comment]
#355
