### ISSUE TITLE
Splitting mzLib

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#351]
## Issue: 
mzLib takes 30 mins to build in AppVeyor

## Possible solution:
Split mzLib down the middle into two different namespaces:

1. **mzLib.Fundamentals**: Chemistry, Chromatography, MassSpectrometry, Proteomics, Spectra, Test, UsefulProteomicsDatabases
2. **mzLib.Mz**: MS1decon, MS2decon, ManagedThermoHelperLayer, Mgf, MzIdentML, MzLibUtil, MzML, PepXML, TestThermo, Thermo, UnmanagedThermoHelperLayer

I'm not sure where FlashLFQ and TestFlashLFQ would go.

## Possible solution 2:

1. **mzLib.Proteomics**: Chromatography, FlashLFQ, MassSpectrometry, Proteomics, Spectra, Test, TestFlashLFQ, UsefulProteomicsDatabases
2. **mzLib.Mz**: Chemistry, MS1decon, MS2decon, ManagedThermoHelperLayer, Mgf, MzIdentML, MzLibUtil, MzML, PepXML, TestThermo, Thermo, UnmanagedThermoHelperLayer

**Comment by zrolfs** [comment]
We could split it up into strictly proteomic related things (digestion, database loading, proteomics, flashLFQ) and mass spec related things (Chemistry, ms loading, mzlibUtil, spectra, decon, Chromatography)?

**Comment by acesnik** [comment]
Chemistry is used in Proteomics

**Comment by zrolfs** [comment]
Lots of things are used in proteomics. Proteomics would be dependent on the mass spec namespace.

**Comment by acesnik** [comment]
That said, Chemistry is rarely modified

**Comment by acesnik** [comment]
I'd be on board with Zach's suggestion. Updated above

**Comment by rmillikin** [comment]
I'm ok with this

My opinion of the delineations:
- FlashLFQ (separate NuGet package)
- Decon executables (separate GitHub repo, not published on Nuget, etc)
- Spectra File/results I/O (mgf, mzML, Thermo .raw[w/ thermo helper layers], pepXML)
- Everything else (mass spec, proteomics, chromatography, chemistry, etc)

**Comment by stefanks** [comment]
I tried to split mzLib way back, it was hellish to manage!

**Comment by acesnik** [comment]
@stefanks Thanks for chiming in! Splitting it would make debugging interlaced code pretty tough, but I'm still tempted to do this because some portions of the code base are rarely touched (especially spectral file classes), and they don't need to be retested each time we change `Protein.cs` and such.

**Comment by acesnik** [comment]
It only takes around 8 mins, now, so this is no longer such an issue.
