### ISSUE TITLE
what do we do with this?  it looks like something else

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/mzLib#359]
namespace Proteomics.ProteolyticDigestion
{
    public enum ModificationType
    {
        AminoAcidResidue,
        ProteinNTerminus,
        ProteinCTerminus,
        PeptideNTerminus,
        PeptideCTerminus
    }
}

**Comment by trishorts** [comment]
namespace Proteomics
{
    public enum TerminusLocalization
    {
        NPep,
        PepC,
        NProt,
        ProtC,
        Any
    }
}

**Comment by trishorts** [comment]
public static string ModLocationOnPeptideOrProtein(string _locationRestriction)
        {
            switch (_locationRestriction)
            {
                case "N-terminal.":
                    return _locationRestriction;

                case "C-terminal.":
                    return _locationRestriction;

                case "Peptide N-terminal.":
                    return _locationRestriction;

                case "Peptide C-terminal.":
                    return _locationRestriction;

                case "Anywhere.":
                    return _locationRestriction;

                default:
                    return "Unassigned.";
            }
        }

**Comment by acesnik** [comment]
It looks like this redundancy was resolved. This is the only one left: https://github.com/smith-chem-wisc/mzLib/blob/85de87b84d2683f54a9ef4fdaa92c646c767790e/Proteomics/Modifications/ModLocationOnPeptideOrProtein.cs.
