### ISSUE TITLE
Error in <binaryDataArrayList> count property 

### ISSUE THREAD

**Issue by ypriverol** [smith-chem-wisc/mzLib#367]
We have used the mzML writer to write some mzML files. We have found an error when it wrote the last <binaryDataArrayList> it does not export the count number. This makes our validator fails.  

The mzML we have generated using your library is here: https://drive.google.com/file/d/1NDfrADkpHm1I69RdnP6uiHrCf6VjK2AW/view?usp=sharing

**Comment by zrolfs** [comment]
To clarify, is the count number the scan specific identifier, such that each spectrum has it's own unique number?

**Comment by zrolfs** [comment]
Specifically, do you know if your validation is failing because the mzML is missing the following line:
"          <cvParam cvRef="MS" accession="MS:1000797" name="peak list scans" value="integer"/>"

**Comment by ypriverol** [comment]
Thanks for your quick reply. The problem is that the <binaryDataArrayList> should contains the **count** property and the las element do not contains it.

Best Regards 
Yasset

**Comment by rmillikin** [comment]
Hi Yasset,

I think we are going to need some more details to fix this problem. Specifically, I think I need to see more details about the error message. The "count" property appears to be in a lot of different places in an mzML file. Can you share your mzML validator with us? Is it on GitHub?

**Comment by ypriverol** [comment]
We have fix the problem in our side.
