### ISSUE TITLE
Using PascalCase for fragment types

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#380]
https://github.com/smith-chem-wisc/mzLib/blob/master/Proteomics/AminoAcidPolymer/FragmentTypes.cs#L29

I think we should use camel case here for style and clarity, even though it's technically not how the fragment types are written in the mass spec literature. For glycans, if we add those fragment types eventually, we should differentiate them in this enumerable in some way other than case. Possibly `FragmentType.A` for peptides and `FragmentType.AGlycan` or `FragmentType.BigA` for glycans.

**Comment by rmillikin** [comment]
Personally I disagree; in general I think all other things being equal, camel/pascal case is great. But here, b and B ions are very different things. In other words, "all other things being equal" does not apply. Programming-wise I agree with you but chemistry-wise I disagree, and the chemistry side trumps things here for me IMO

**Comment by acesnik** [comment]
Yep, it's a balance of naming conventions: chemistry has made them short and sweet and case-dependent for concise manual annotation, and programming languages have made them longer and systematically cased to avoid confusion and bugs between variable names.
