### ISSUE TITLE
Loading elements always

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#440]
1. Figure out how to copy text files into nuget packages (using nuspec file) and get them into a build directory of another program (using mzLib.targets).
2. Put `elements.dat` file into the `UsefulProteomicsDatabases` project and copy with nuspec and mzLib.targets.
3. `Loaders` static constructor should load elements from the file.
4. Checking for updates takes longer, so probably not something to do in the `Loaders` constructor. But something to consider...

**Comment by acesnik** [comment]
Here is an example of where it's been confusing for others:
https://github.com/compomics/ThermoRawFileParser/blob/b8179db696a2ceb602e4ed275b72fcc6b5fba632/ThermoRawFileParserTest/Tests.cs#L27

**Comment by rmillikin** [comment]
I had a really hard time getting the nuget package to copy elements.dat to the correct place and be able to reference the path. I ended up just adding the entire elements database to the .cs file as a string. probably the hackiest solution imaginable, but it works. I also added a line of code to see if the periodic table has already been loaded, before loading it. #447

**Comment by acesnik** [comment]
Isn't that nuget packaging of content files awful? I couldn't figure it out, either.

**Comment by acesnik** [comment]
See also https://github.com/smith-chem-wisc/mzLib/issues/354
