### ISSUE TITLE
GTPMD variant decoy crash (again)

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#476]
[results.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/3149996/results.txt)

"\\bison\share\Projects\JurkatProteogenomics\VariantGPTMDCrash\combined.spritz.tr.snpeff.protein.withmodsGPTMD.xml"

@rmmiller22 Could you debug this one?

**Comment by acesnik** [comment]
See `Test\DatabaseTests\TestVariantProtein.cs` and `Test\DatabaseTests\TestProteinReader.cs` for some examples of related tests.

**Comment by rmmiller22** [comment]
Yeah I will try and see whats bugging out and fix it
