### ISSUE TITLE
Create icon for mzLib

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#573]
Might be nice to create an icon for mzLib, so that it can be put in powerpoints etc.

Also, it can be used as a badge in nuget using the nuspec icon field, e.g. https://github.com/nunit/nunit/blob/master/nuget/framework/nunit.nuspec#L13.

**Comment by trishorts** [comment]
thoughts on these?
![image](https://user-images.githubusercontent.com/16841846/113865830-2f444000-9772-11eb-9101-98271589fedf.png)

**Comment by acesnik** [comment]
That first one is my favorite 👍🏼

**Comment by trishorts** [comment]
![mzLibIcon64](https://user-images.githubusercontent.com/16841846/113908189-df7a6e80-979b-11eb-9a2d-571a53e167ac.png)
![mzLibIcon48](https://user-images.githubusercontent.com/16841846/113908191-e0130500-979b-11eb-8fc9-645468da8c92.png)
![mzLibIcon32](https://user-images.githubusercontent.com/16841846/113908193-e0130500-979b-11eb-93c3-2b454f076def.png)
![mzLibIcon16](https://user-images.githubusercontent.com/16841846/113908195-e0ab9b80-979b-11eb-9670-3e7b2bdfb7a4.png)

**Comment by trishorts** [comment]
[Uploading mzLibIconsSizes.zip…]()

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/mzLib/pull/585

**Comment by acesnik** [comment]
https://github.com/smith-chem-wisc/mzLib/pull/585

**Comment by acesnik** [comment]
Looks great! <img width="977" alt="image" src="https://user-images.githubusercontent.com/16342951/128513884-d5e2c652-beb9-44f6-89c3-ead57b134b6f.png">
