### ISSUE TITLE
Kullback-Leibler Divergence is 0 if no peaks match

### ISSUE THREAD

**Issue by Alexander-Sol** [smith-chem-wisc/mzLib#644]
Kullback-Leibler Divergence has a lower bound of 0, with lower scores being better. In the current implementation, a pair of spectra with no peaks in common would receive a score of 0. 

A quick fix would be to add a new normalization scheme, spectrum sum + 1, where you add one to every experimental intensity values. 

However, this scheme couldn't be applied to the theoretical intensity values in cases where you pass in a theoretical isotope distribution. So you would have to normalize the experimental and theoretical intensity arrays differently.

**Comment by trishorts** [comment]
i think this should return null. B/c if there are no matched peaks then nothing else happens

**Comment by Alexander-Sol** [comment]
> i think this should return null. B/c if there are no matched peaks then nothing else happens

Agreed. I edited the PR. In situations where no peaks match, it returns null. If there is at least one matching peak, a correction occurs
