### ISSUE TITLE
extra trailing tab in output

### ISSUE THREAD

**Issue by jvolkening** [smith-chem-wisc/mzLib#657]
(Originally posted to smith-chem-wisc/FlashLFQ/issues/120)

Just noticed that FlashLFQ output files ("QuantifiedPeptides.tsv", etc) have a trailing tab at the end of each line, at least on Linux command line version. Currently running version 1.2.4, but looking back I find the same thing in old files as well. Not a big deal, but confuses R/readr a bit and may possibly confuse other downstream software as well.

Looks like maybe a fix could be in FlashLFQResults.cs -> `WriteResults` method, e.g. by adding `TrimEnd("\t")` to the various line-printing statements.

**Comment by trishorts** [comment]
Fixed in https://github.com/smith-chem-wisc/mzLib/pull/658
Will take time for this update to make its way through to a new release of FlashLFQ.
Thanks for the report.

**Comment by jvolkening** [comment]
Thanks!
