### ISSUE TITLE
GO Terms in ProteinDbLoader

### ISSUE THREAD

**Issue by acesnik** [smith-chem-wisc/mzLib#80]
ProteoformSuite uses GO terms, and I expect we will use them with a quantitation side of MetaMorpheus.

Could we make a couple new classes in the Proteomics namespace: GoTerm and ProteinWithGoTerms?

```
public class GoTerm
    {
        public string id { get; set; }
        public string description { get; set; }
        public Aspect aspect { get; set; }
    }

    public enum Aspect
    {
        molecularFunction,
        cellularComponent,
        biologicalProcess
    }
```

```
    public class ProteinWithGoTerms : Protein
    {
             public List<GoTerm> goTerms { get; set; }
             //Constructor with the goTerms list

```
As for the ProteinDbReader, I found the nested switch-cases with XmlReader confusing, so I changed it to the processing XElement objects with LINQ a while back. Here is a snippet of that code for getting the GO Terms from protein entries. I'm not exactly sure where we would pull out the GO information, but it would probably involve working the "dbReference" into the nested switches. @stefanks would you be interested in switching over to XElement for somewhat easier tracing? ([Here it is in the ProteoformSuite code.](https://github.com/smith-chem-wisc/proteoform-suite/blob/master/ProteoformSuiteInternal/ProteomeDatabaseReader.cs#L141))

 ```
List<XElement> dbReferences = entry.Elements().Where(node => node.Name.LocalName == "dbReference").ToList();
//Process dbReferences to retrieve Gene Ontology Terms
foreach (XElement dbReference in dbReferences)
{
	string dbReference_type = GetAttribute(dbReference, "type");
	if (dbReference_type == "GO")
	{
		GoTerm go = new GoTerm();
		string ID = GetAttribute(dbReference, "id");
		go.id = ID.Split(':')[1].ToString();
		IEnumerable<XElement> dbProperties = from XElement in dbReference.Elements() where XElement.Name.LocalName == "property" select XElement;

		foreach (XElement property in dbProperties)
		{
			string type = GetAttribute(property, "type");
			if (type == "term")
			{
				string description = GetAttribute(property, "value");
				switch (description.Split(':')[0].ToString())
				{
					case "C":
						go.aspect = Aspect.cellularComponent;
						go.description = description.Split(':')[1].ToString();
						break;
					case "F":
						go.aspect = Aspect.molecularFunction;
						go.description = description.Split(':')[1].ToString();
						break;
					case "P":
						go.aspect = Aspect.biologicalProcess;
						go.description = description.Split(':')[1].ToString();
						break;
				}
				goTerms.Add(go);
			}
		}
	}
}

```

**Comment by stefanks** [comment]
Switching to XElement would be fine, if you are willing to make a pull request and unit tests 👍 

I'm not sure what these GO terms are, you'll have to explain them to me.

**Comment by stefanks** [comment]
We should also consider using the official schema to read xml files
http://www.uniprot.org/docs/uniprot.xsd
